openapi: 3.0.1
info:
  title: BEERFINDER - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: http://beerfinder.test/api/records/
    variables: {}
    description: Entorno React
tags:
  - name: users
    description: Operaciones con los usuarios
  - name: beers
    description: Operaciones con las beers
  - name: locals
    description: Operaciones con los locals
  - name: beerlocals
    description: Operaciones con los beerlocals
  - name: visits
    description: Operaciones con las visits
paths:
  /users:
    get:
      tags:
        - users
      summary: Obtener todos los usuarios
      description: Obtener todos los usuarios
      operationId: users.index
      responses:
        "200":
          description: Usuarios obtenidos correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/usersIndexResponse"
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /beers:
    get:
      tags:
        - beers
      summary: Obtener todas las beers
      description: Obtener todas las beers
      operationId: beers.index
      responses:
        "200":
          description: Beers obtenidas correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/beersIndexResponse"
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /locals:
    get:
      tags:
        - locals
      summary: Obtener todos los locals
      description: Obtener todos los locals
      operationId: locals.index
      responses:
        "200":
          description: Locals obtenidos correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/localsIndexResponse"
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /beerlocals:
    get:
      tags:
        - beerlocals
      summary: Obtener todos los beerlocals
      description: Obtener todos los beerlocals
      operationId: beerlocals.index
      responses:
        "200":
          description: Beerlocals obtenidos correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/beerlocalsIndexResponse"
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /visits:
    get:
      tags:
        - visits
      summary: Obtener todas las visits
      description: Obtener todas las visits
      operationId: visits.index
      responses:
        "200":
          description: Visits obtenidas correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/visitsIndexResponse"
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        email_verified_at:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - id
        - name
        - email
        - email_verified_at
        - created_at
        - updated_at
      xml:
        name: userss
    Beer:
      type: object
      properties:
        id:
          type: integer
        users_id:
          type: integer
        name:
          type: string
        color:
          type: string
        graduation:
          type: float
        taste:
          type: string
        type:
          type: string
        description:
          type: string
        image:
          type: string
        country:
          type: string
        region:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - id
        - name
        - users_id
        - color
        - graduation
        - taste
        - type
        - description
        - image
        - country
        - region
        - created_at
        - updated_at
      xml:
        name: Beers
    Local:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        users_id:
          type: integer
        type:
          type: string
        description:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string
        latitude:
          type: string
        longitude:
          type: string
        city:
          type: string
        region:
          type: string
        website:
          type: string
        image:
          type: string
        verified:
          type: boolean
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - id
        - name
        - users_id
        - type
        - description
        - email
        - phone
        - address
        - latitude
        - longitude
        - city
        - region
        - website
        - image
        - verified
        - created_at
        - updated_at
      xml:
        name: Locals
    Beerlocal:
      type: object
      properties:
        id:
          type: integer
        beer_id:
          type: integer
        local_id:
          type: integer
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - id
        - beer_id
        - local_id
        - created_at
        - updated_at
      xml:
        name: Beerlocals
    Visit:
      type: object
      properties:
        id:
          type: integer
        count:
          type: integer
      required:
        - id
        - count
      xml:
        name: Visits
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
      type:
        type: string
      message:
        type: string
    required:
      - code
      - type
      - message
    xml:
      name: ApiResponses
    requestBodies:
      User:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/users"
      Beer:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Beer"
      Local:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Local"
      Beerlocal:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Beerlocal"
      Visit:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Visit"
    securitySchemes:
      basic_auth:
        type: http
        scheme: basic
